name: Video_hole_plus_player_demo

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  http: ^0.13.0
  event: ^2.1.2
  get_it: ^7.2.0
  video_player_avplay: 
    path: /home/guanxw/tizen/plugins/packages/video_player_avplay

dev_dependencies:
  build_runner: 2.4.6
  flutter_lints: ^2.0.0
  freezed: ^2.3.2

flutter:
  uses-material-design: true